/*
 * Copyright 2003-2026 The IdeaVim authors
 *
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE.txt file or at
 * https://opensource.org/licenses/MIT.
 */

package com.maddyhome.idea.vim.key

import java.awt.event.KeyEvent

enum class KeySource(val allowsKeyMapping: Boolean) {
  /**
   * The key was typed by a user
   *
   * Not to be confused with [KeyEvent.KEY_TYPED] and [KeyEvent.KEY_PRESSED]! Whether the key even is typed or pressed,
   * the source is the user typing. The key can be mapped, both by `'langmap'` and user maps.
   */
  TYPED(true),

  /**
   * The key is the result of a mapping
   *
   * Mappings are recursive by default, so this key can be mapped further with user maps. If `'langremap'` is set, then
   * the key can be mapped again by `'langmap'`.
   */
  MAPPED(true),

  /**
   * The key is the result of a non-recursive mapping
   *
   * The key will not be mapped by user maps, but if `'langremap'` is set, then the key can be mapped again by
   * `'langmap'`.
   */
  MAPPED_NON_RECURSIVE(false),

  /**
   * The key is a result of mapping according to `'langmap'`
   *
   * The key can be mapped further by user maps, but will not map with `'langmap'` again.
   */
  LANG_MAP(true),

  /**
   * The key is being replayed from the start of a mapping prefix that failed to match
   *
   * For example, given a mapping `dwxxx`, typing `dwy` will replay `dw`. The first `d` must not be mapped, or we'll get
   * stuck in an endless loop.
   */
  MAPPING_PREFIX_REPLAY(false),

  /**
   * The key was generated from a digraph with `<C-K>` or `<C-Q>`
   *
   * The key will be mapped.
   */
  DIGRAPH(true),

  /**
   * The key was generated as a literal value with `<C-V>`
   *
   * The key will be mapped
   */
  LITERAL(true),

  /**
   * The key was created by playing back a macro
   *
   * Mappings are allowed.
   */
  MACRO_PLAYBACK(true),

  /**
   * Key was generated by the `:normal` command. Treated as though it was typed.
   *
   * The key will be mapped.
   */
  NORMAL_COMMAND(true),

  /**
   * The key was generated by the `:normal!` command, with no mappings allowed
   */
  NORMAL_COMMAND_NOT_MAPPED(false),

  /**
   * Used internally by IdeaVim to push keystrokes through the key handler pipeline
   *
   * This allows IdeaVim to insert a sequence of keystrokes as if they were typed literally, but without mapping
   * applied. The main use case is inserting keystrokes from a register or the current word.
   */
  SYNTHETIC_TYPED_NOT_MAPPED(false)
}
