package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'MergeDependabotPr'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("MergeDependabotPr")
    name = "Merge Dependabot PR"
    description = "Automatically merge dependency bump pull request"

    vcs {
        root(RelativeId("HttpsGithubComJetBrainsIdeavimRefsHeadsMaster"))
    }

    steps {
        gradle {
            tasks = "clean build"
            gradleWrapperPath = ""
        }
    }

    triggers {
        vcs {
            branchFilter = "+:dependabot/*"
        }
    }

    features {
        perfmon {
        }
    }
}))

