package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Nvim'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Nvim")) {
    expectSteps {
        script {
            name = "Set up NeoVim"
            scriptContent = """
                wget https://github.com/neovim/neovim/releases/download/v0.4.4/nvim-linux64.tar.gz
                tar xzf nvim-linux64.tar.gz
                cd nvim-linux64/bin
                chmod +x nvim
            """.trimIndent()
        }
        gradle {
            tasks = "clean testWithNeovim"
            buildFile = ""
            enableStacktrace = true
            param("org.jfrog.artifactory.selectedDeployableServer.defaultModuleVersionConfiguration", "GLOBAL")
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                wget https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.tar.gz
                tar xzf nvim-linux64.tar.gz
                cd nvim-linux64/bin
                chmod +x nvim
            """.trimIndent()
        }
    }
}
