package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.VcsLabeling
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.vcsLabeling
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseEap'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseEap")) {
    features {
        val feature1 = find<VcsLabeling> {
            vcsLabeling {
                vcsRootId = "${DslContext.settingsRoot.id}"
                labelingPattern = "%system.build.number%"
                successfulOnly = true
                branchFilter = ""
            }
        }
        feature1.apply {
            successfulOnly = false
        }
    }
}
