package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseEap'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseEap")) {
    params {
        expect {
            password("env.YOUTRACK_TOKEN", "credentialsJSON:2479995b-7b60-4fbb-b095-f0bafae7f622", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.YOUTRACK_TOKEN", "credentialsJSON:eedfa0eb-c329-462a-b7b4-bc263bda8c01", display = ParameterDisplay.HIDDEN)
        }
    }
}
