package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Release_201'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Release_201")) {
    params {
        expect {
            password("env.ORG_GRADLE_PROJECT_publishToken", "credentialsJSON:ec1dc748-e289-47e1-88b6-f193d7999bf4", label = "Password")
        }
        update {
            password("env.ORG_GRADLE_PROJECT_publishToken", "credentialsJSON:61a36031-4da1-4226-a876-b8148bf32bde", label = "Password")
        }
        expect {
            param("env.ORG_GRADLE_PROJECT_publishUsername", "vlan")
        }
        update {
            param("env.ORG_GRADLE_PROJECT_publishUsername", "Aleksei.Plate")
        }
    }
}
