package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseMinor'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseMinor")) {
    check(artifactRules == "build/distributions/*") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        build/distributions/*
        build/reports/*
    """.trimIndent()
}
