package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseDev'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseDev")) {
    expectSteps {
        script {
            name = "Pull git tags"
            scriptContent = "git fetch --tags origin"
        }
        script {
            name = "Pull git history"
            scriptContent = "git fetch --unshallow"
        }
        gradle {
            name = "Calculate new dev version"
            tasks = "scripts:calculateNewDevVersion"
        }
        gradle {
            name = "Set TeamCity build number"
            tasks = "scripts:setTeamCityBuildNumber"
        }
        gradle {
            tasks = "publishPlugin"
        }
    }
    steps {
        update<GradleBuildStep>(2) {
            clearConditions()
            jdkHome = "%env.JDK_17_0%"
        }
    }
}
