package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SlackNotificationTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SlackNotificationTest")) {
    params {
        expect {
            password("env.ANTHROPIC_API_KEY", "credentialsJSON:712a6516-4f43-41dc-b9e9-e32b1453dde8", label = "Anthropic API Key", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.ANTHROPIC_API_KEY", "credentialsJSON:95f0b3f7-16c5-46f8-9c3c-db45456556f9", label = "Anthropic API Key", display = ParameterDisplay.HIDDEN)
        }
    }
}
