package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'UpdateAuthors'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("UpdateAuthors")) {
    params {
        add {
            password("env.ORG_GRADLE_PROJECT_updateAuthorsToken", "credentialsJSON:fc75a88f-fd02-46af-899a-a5034f402b7e", label = "Password", display = ParameterDisplay.HIDDEN)
        }
    }
}
