package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.AmazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.amazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AmazonEC2CloudImage> {
            amazonEC2CloudImage {
                id = "PROJECT_EXT_768"
                profileId = "amazon-48"
                agentPoolId = "41"
                name = "BuildAgentsIdeaVim"
                vpcSubnetId = "subnet-58839511"
                keyPairName = ""
                instanceType = "c5d.xlarge"
                securityGroups = listOf("sg-eda08696", "sg-7332cf0f")
                useSpotInstances = true
                instanceTags = mapOf(
                    "project" to "idea-vim"
                )
                source = Source("ami-0fa17ce8238eb8868")
                param("image-instances-limit", "")
                param("spot-instance-price", "")
            }
        }
        feature1.apply {
            profileId = "amazon-48"
            agentPoolId = "41"
            name = "BuildAgentsIdeaVim"
            vpcSubnetId = "subnet-58839511"
            keyPairName = ""
            instanceType = "c5d.xlarge"
            securityGroups = listOf("sg-eda08696", "sg-7332cf0f")
            useSpotInstances = true
            instanceTags = mapOf(
                "project" to "idea-vim"
            )
            source = Source("ami-07c529efaddafcf86")
        }
    }
}
