package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GitHubPullRequest'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GitHubPullRequest")) {
    val expected = GitVcsRoot({
        id("GitHubPullRequest")
        name = "IdeaVim Pull Requests"
        url = "git@github.com:JetBrains/ideavim.git"
        branchSpec = "+:refs/(pull/*)/head"
        authMethod = uploadedKey {
            uploadedKey = "Alex Plate TeamCity key"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branch = "master"
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "IdeaVim ssh keys"
            passphrase = ""
        }
    }

}
