package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComAlexPl292IdeaVimCompatibilityRefsHeadsMaster'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComAlexPl292IdeaVimCompatibilityRefsHeadsMaster")
    name = "https://github.com/AlexPl292/IdeaVimCompatibility#refs/heads/master"
    url = "https://github.com/AlexPl292/IdeaVimCompatibility"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "AlexPl292"
        password = "credentialsJSON:43afd6e5-6ad5-4d12-a218-cf1547717a7f"
    }
    param("oauthProviderId", "PROJECT_EXT_1")
}))

