package com.maddyhome.idea.vim.vimscript.model.expressions.operators.handlers.binary

object DoesntMatchHandler : BinaryOperatorWithIgnoreCaseOption(DoesntMatchIgnoreCaseHandler, DoesntMatchCaseSensitiveHandler)
