package com.maddyhome.idea.vim.vimscript.model.expressions.operators.handlers.binary

object LessOrEqualsHandler : BinaryOperatorWithIgnoreCaseOption(LessOrEqualsIgnoreCaseHandler, LessOrEqualsCaseSensitiveHandler)
